
name: HTML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Custom
        run: echo "Hello World" 
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '20.16.0'
      - name: Deploy
        run: netlify deploy --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --dir="." --prod
          
